const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const money = n => new Intl.NumberFormat('pt-MZ', { maximumFractionDigits: 0 }).format(n) + ' MT';
const data = {presenca:[72,85,64,91,78,102,88,132],dept:[['Administração',48200],['JNI',22500],['MNI',18450],['DNI',15200],['Louvor',9700]],visitantesTipo:[['1ª visita',9],['Retorno',8],['Sem indicação',6]],origem:[['Convite de membro',11],['Redes sociais',5],['Família',4],['Passagem pela igreja',3]],cultos:[{titulo:'1º Culto Dominical',data:'11/05/2026',local:'Templo principal',pax:132,visitantes:6,dizimos:30960,ofertas:12200,total:43160},{titulo:'2º Culto Dominical',data:'11/05/2026',local:'Templo principal',pax:88,visitantes:3,dizimos:18450,ofertas:7600,total:26050},{titulo:'Culto de Oração',data:'14/05/2026',local:'Sala de oração',pax:56,visitantes:1,dizimos:4200,ofertas:2100,total:6300}],escalas:[['11/05/2026','08:00','1º Culto','Dirigente','Helena António','84 000 0000'],['11/05/2026','08:00','1º Culto','Pregador','Pr. Alberto Mudumbe','82 000 0000'],['11/05/2026','10:00','2º Culto','Louvor','Telma Hlavangwane','85 000 0000'],['14/05/2026','18:00','Culto de Oração','Acolhimento','Joana Magaia','86 000 0000']],visitantes:[['11/05/2026','Lurdes Cossa','Tchumene','Sim','Sim','84 222 1111'],['11/05/2026','Feliciano Mucavele','Matola','Não','Sim','85 111 3333'],['14/05/2026','Argentina Tembe','Ndlavela','Sim','Não','—']],finance:[['Caixa físico',58600,46200,39100,7100,65700],['M-Pesa',0,38840,12230,26610,26610],['E-Mola',0,14400,7200,7200,7200],['Conta bancária',0,30000,45200,-15200,-15200]],rubricas:[['Dízimos',72840],['Ofertas gerais',32400],['Escola Dominical',9600],['Missões',7200],['Juventude',3400]],delegados:[['Efectivo','Alberto Mudumbe','84 000 0000','Delegado eleito'],['Efectivo','Joana Magaia','85 000 0000','Delegada eleita'],['Efectivo','Filipe Cossa','86 000 0000','Delegado eleito'],['Ex officio','Pastor Local','82 000 0000','Por função'],['Suplente','Marta Nhantumbo','87 000 0000','Substituição']],fases:[['1','Preparação na Igreja Local','Encerramento estatístico, contas, relatórios e comissão local.'],['2','Reunião Anual da Igreja Local','Relatórios, eleições e certificado de delegados.'],['3','Preparação Ministerial Individual','Relatórios ministeriais, licenças e ordenações.'],['4','Organização Distrital Pré-Assembleia','Logística, credenciais, protocolo e documentação.'],['5','Dia da Assembleia Distrital','Registo, relatórios, eleições e encerramento.']]};
function rank(el, rows){$(el).innerHTML=rows.map(([label,val])=>`<div class="rank-row"><span>${label}</span><b>${typeof val==='number'&&val>1000?money(val):val}</b></div>`).join('');}
function rows(el, arr){$(el).innerHTML=arr.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('');}
function initOverview(){const max=Math.max(...data.presenca);$('#bars').innerHTML=data.presenca.map((v,i)=>`<div class="bar"><span style="height:${Math.max(18,v/max*100)}%"></span><small>${i+1}º</small></div>`).join('');rank('#rankDept',data.dept);rank('#rankVisitantes',data.visitantesTipo);rank('#rankOrigem',data.origem);}
function initCultos(){$('.culto-list').innerHTML=data.cultos.map(c=>`<article class="culto-card"><header><div><h3>${c.titulo}</h3><small>${c.data} · ${c.local}</small></div><b>${c.pax} PAX</b></header><div class="culto-stats"><div><small>Visitantes</small><b>${c.visitantes}</b></div><div><small>Dízimos</small><b>${money(c.dizimos)}</b></div><div><small>Ofertas</small><b>${money(c.ofertas)}</b></div><div><small>Total</small><b>${money(c.total)}</b></div><div><small>Sta. Ceia</small><b>Sim</b></div></div></article>`).join('');}
function initTables(){rows('#escalaRows',data.escalas);rows('#visitanteRows',data.visitantes);rows('#financeRows',data.finance.map(r=>[r[0],money(r[1]),money(r[2]),money(r[3]),money(r[4]),money(r[5])]));rows('#delegadoRows',data.delegados);rank('#rubricasFinance',data.rubricas);rank('#deptFinance',data.dept);$('#timeline').innerHTML=data.fases.map(f=>`<div class="phase"><span>${f[0]}</span><div><strong>${f[1]}</strong><p>${f[2]}</p></div></div>`).join('');}
function switchView(v){$$('.demo-nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v).classList.add('active');$('#viewTitle').textContent=$(`.demo-nav[data-view="${v}"]`).textContent.trim();}
$$('.demo-nav').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view)));$$('.module-grid button').forEach(btn=>btn.addEventListener('click',()=>{location.hash='demo';setTimeout(()=>switchView(btn.dataset.open),120);}));$('#simulateBtn').addEventListener('click',()=>{const t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200);});initOverview();initCultos();initTables();
